# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AMM Periphery Quality Test

env:
  FOUNDRY_PROFILE: amm-periphery

on:
  push:
    branches: [ master, develop ]
    paths:
      - silo-amm-periphery/**/*.sol
      - silo-amm-periphery/**/*.ts
      - silo-amm-periphery/**/*.js
      - silo-amm-periphery/**/*.json

  pull_request:
    paths:
      - silo-amm-periphery/**/*.sol
      - silo-amm-periphery/**/*.ts
      - silo-amm-periphery/**/*.js
      - silo-amm-periphery/**/*.json

jobs:

  build:
    name: AMM Periphery job
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: yarn install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Solidity Lint
        run: yarn workspace silo-amm-periphery lint:sol

      - name: Solidity Foundry Tests
        run: yarn workspace silo-amm-periphery test
