# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: AMM Quality Test

env:
  FOUNDRY_PROFILE: amm

on:
  push:
    branches: [ master, develop ]
    paths:
      - silo-amm/**/*.sol
      - silo-amm/**/*.ts
      - silo-amm/**/*.js
      - silo-amm/**/*.json

  pull_request:
    paths:
      - silo-amm/**/*.sol
      - silo-amm/**/*.ts
      - silo-amm/**/*.js
      - silo-amm/**/*.json

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: yarn install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Solidity Lint
        run: yarn workspace silo-amm lint:sol

      - name: Solidity Foundry Tests
        run: yarn workspace silo-amm test
