# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CORE Quality Test

env:
  FOUNDRY_PROFILE: core
  RPC_MAINNET: ${{ vars.RPC_MAINNET }}
  RPC_ARBITRUM: ${{ vars.RPC_ARBITRUM }}
  RPC_SEPOLIA: ${{ vars.RPC_SEPOLIA }}
  PRIVATE_KEY: ${{ vars.ANVIL_PRIVATE_KEY }}

on:
  push:
    branches: [ master, develop ]
    paths:
      - silo-core/**/*.sol
      - silo-core/**/*.ts
      - silo-core/**/*.js
      - silo-core/**/*.json
      - package.json
      - yarn.lock
      - gitmodules/*
      - .gitmodules

  pull_request:
    paths:
      - silo-core/**/*.sol
      - silo-core/**/*.ts
      - silo-core/**/*.js
      - silo-core/**/*.json
      - package.json
      - yarn.lock
      - gitmodules/*
      - .gitmodules

jobs:

  linters:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install

      - name: Solidity Lint
        run: yarn workspace silo-core lint:sol

  foundry:
    name: Foundry QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-2fc85cb4a2d296b916a413f9f13caadebcf4cf47

      - name: Run Forge build
        run: |
          git submodule
          forge --version
          # forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv --no-match-test "_skip_" --ffi
