# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VAULTS Quality Test

env:
  FOUNDRY_PROFILE: vaults

on:
  push:
    branches: [ master, develop ]
    paths:
      - silo-vaults/**/*.sol
      - silo-vaults/**/*.ts
      - silo-vaults/**/*.js
      - silo-vaults/**/*.json

  pull_request:
    paths:
      - silo-vaults/**/*.sol
      - silo-vaults/**/*.ts
      - silo-vaults/**/*.js
      - silo-vaults/**/*.json

jobs:

  linters:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn workspace silo-vaults install

      - name: Solidity Lint
        run: yarn workspace silo-vaults lint:sol


  foundry:
    name: Foundry QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: yarn install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

      - name: Run Forge tests
        run: forge test -vvv
