name: Uniswap V2 periphery - CI

on:
  push:
    branches: [ master, develop ]
    paths:
      - external/uniswap-v2-periphery/**/*.sol
      - external/uniswap-v2-periphery/**/*.ts
      - external/uniswap-v2-periphery/**/*.js
      - external/uniswap-v2-periphery/**/*.json

  pull_request:
    paths:
      - external/uniswap-v2-periphery/**/*.sol
      - external/uniswap-v2-periphery/**/*.ts
      - external/uniswap-v2-periphery/**/*.js
      - external/uniswap-v2-periphery/**/*.json

jobs:
  test:
    strategy:
      matrix:
        node: [ 18.x ]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: npm install -g yarn

      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-yarn-

      - run: yarn workspace uniswap-v2-periphery install

      - run: yarn workspace uniswap-v2-periphery compile
      - run: yarn workspace uniswap-v2-periphery lint
      - run: yarn workspace uniswap-v2-periphery test
